
spring:
  datasource:
    url: jdbc:h2:file:./data/hlr-bot
    username: ca
    password:
    initialization-mode: always
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true


telegram-bot:
  name:
  token:

integration:
  bsg:
    x-api-key:
