spring:
  datasource:
    url: jdbc:h2:file:./data/hlr-bot
    username: ca
    password:
    initialization-mode: always
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true


integration:
  bsg:
    hlr-statuses:
      finalized:
        - absent
        - active
        - barred
        - failed
        - unknown
      pending:
        - sent
    async-hlr-info:
      limit: 10
      pause: 1000
