spring:
  datasource:
    url: jdbc:h2:file:./data/hlr-bot
    username: ca
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  sql:
    init:
      mode: ALWAYS
  flyway:
    locations: db/migration/h2

bot:
  name:
  token:
  languages:
    - en
    - uk
    - ru
  limit-of-numbers: 3
  file:
    max-size: 5
    limit-of-numbers: 3000
  expected-execution-time-per-request-in-milliseconds: 500
  long-execution-message-value-in-minutes: 1

integration:
  urls:
    base-url: https://app.bsg.hk/rest
    request-hlr-info-url: ${integration.urls.base-url}/hlr/
    create-hlr-url: ${integration.urls.base-url}/hlr/create
    balance-url: ${integration.urls.base-url}/common/balance
  bsg:
    max-hlrs-per-request: 1000
    hlr-statuses:
      finalized:
        - absent
        - active
        - barred
        - failed
        - unknown
      pending:
        - sent
    async-hlr-info:
      limit: 10
      pause: 1000

files:
  csv-file-writer-separator: ;
  storage-location: ./temp
  headers:
    regex-list:
      - .*phone.*
      - .*number.*
      - .*телефон.*
      - .*номер.*
